services:

  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./app:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A config.celery worker --loglevel=info --concurrency=4
    volumes:
      - ./app:/app
      - media_volume:/app/media
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A config.celery beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  flower:
    build: .
    command: celery -A config.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper123
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper -d scraperdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
  media_volume:
