# Generated by Django 4.2.29 on 2026-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='headings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedpage',
            unique_together={('site', 'page_url')},
        ),
    ]
