# Generated by Django 4.2.29 on 2026-03-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapedpage_headings_scrapedpage_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scraper.scrapedsite')),
            ],
        ),
        migrations.CreateModel(
            name='ContentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('new_pages', 'New Pages Found'), ('removed_pages', 'Pages Removed'), ('content_change', 'Content Changed'), ('word_count', 'Word Count Changed')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='scraper.scrapedsite')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
