# Generated by Django 4.2.29 on 2026-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scheduledscrape_contentchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedsite',
            name='scrape_depth',
            field=models.IntegerField(default=5),
        ),
    ]
