# Generated by Django 4.2.29 on 2026-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapedsite_scrape_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedsite',
            name='pages_per_second',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedsite',
            name='scrape_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedsite',
            name='scrape_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedsite',
            name='scrape_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
